; When using DICT model, you need to define your resources before the Uniface standard UAR's
; as it is loaded from bottom up instead of top-down
[RESOURCES]
;PLUGIN-SAMPLES.uar
resources

#file USYSADM:ide.asn

#file .\asn\dbms.asn

[SETTINGS]
$putmess_logfile        .\log\ide%p.log
;$resources_output      PLUGIN-SAMPLES.uar
$resources_output       resources
$listing_level			2
$test_mode_components

[FILES]
*.cmi   cmi\*.cmi
*.dtd   dtd\*.dtd
*.*lst	lst\*.*lst
*.*sym	sym\*.*sym

[LOGICALS]
IDETITLE=Uniface 10.3 Custom Worksheet Development

; Custom worksheets
IDE_DEFINE_WORKSHEETS_CPT=WS_LISTING,WS_CHECKSTYLE,WS_STATISTICS

; By default, the templates and palettes used in the Resource Browsers cannot 
; be opened in an editor. If the user wants to create and maintain user defined 
; templates and palettes, the setting 'allow_browse_templates' to browse and 
; open templates should be enabled: default/disabled = 0 ; enabled = 1
; NOTE: Templates and palettes provided by Uniface should not be modified
; without understanding the impact of such modifications.

allow_browse_templates = 0
;allow_browse_templates = 1
